version: '3.8'

services:
  app:
    image: ghcr.io/your-github-username/chat-data-mcp-tools-ui:latest
    ports:
      - "80:8000"
    environment:
      - APP_NAME=Production Chat Bot UI 6
      - LLM_CONFIG_FILE=/app/config/llms.yml
      - TEST_MODE=False
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
