llms:
  - name: "Claude 3.5 Sonnet"
    provider: "anthropic"
    model: "claude-3-5-sonnet-20241022"
    api_key_env: "ANTHROPIC_API_KEY"
    base_url: "https://api.anthropic.com/v1"
    description: "Anthropic's most capable model with advanced reasoning"
    
  - name: "Claude 3.5 Haiku"
    provider: "anthropic"
    model: "claude-3-5-haiku-20241022"
    api_key_env: "ANTHROPIC_API_KEY"
    base_url: "https://api.anthropic.com/v1"
    description: "Fast and lightweight model for quick responses"
    
  - name: "Claude 3.7 Sonnet"
    provider: "anthropic"
    model: "claude-3-7-sonnet-20250219"
    api_key_env: "ANTHROPIC_API_KEY"
    base_url: "https://api.anthropic.com/v1"
    description: "Enhanced Sonnet model with improved capabilities"
    
  - name: "Claude Opus 4"
    provider: "anthropic"
    model: "claude-opus-4-20250514"
    api_key_env: "ANTHROPIC_API_KEY"
    base_url: "https://api.anthropic.com/v1"
    description: "Most powerful Claude model for complex reasoning"
    
  - name: "Claude Sonnet 4"
    provider: "anthropic"
    model: "claude-sonnet-4-20250514"
    api_key_env: "ANTHROPIC_API_KEY"
    base_url: "https://api.anthropic.com/v1"
    description: "Latest Sonnet model with best performance"
    
  - name: "GPT-4 Turbo"
    provider: "openai"
    model: "gpt-4-turbo-preview"
    api_key_env: "OPENAI_API_KEY"
    base_url: "https://api.openai.com/v1"
    description: "OpenAI's latest GPT-4 model with improved performance"
    
  - name: "GPT-3.5 Turbo"
    provider: "openai"
    model: "gpt-3.5-turbo"
    api_key_env: "OPENAI_API_KEY"
    base_url: "https://api.openai.com/v1"
    description: "Fast and efficient model for most conversational tasks"
