llms:
  - name: "Claude 3.5 Sonnet"
    provider: "anthropic"
    base_url: "https://api.anthropic.com/v1"
    api_key: "${LLM_API_KEY}"
    model_name: "claude-3-5-sonnet-20241022"
    
  - name: "Claude 3.5 Haiku"
    provider: "anthropic"
    base_url: "https://api.anthropic.com/v1"
    api_key: "${LLM_API_KEY}"
    model_name: "claude-3-5-haiku-20241022"
    
  - name: "Claude 3.7 Sonnet"
    provider: "anthropic"
    base_url: "https://api.anthropic.com/v1"
    api_key: "${LLM_API_KEY}"
    model_name: "claude-3-7-sonnet-20250219"
    
  - name: "Claude Opus 4"
    provider: "anthropic"
    base_url: "https://api.anthropic.com/v1"
    api_key: "${LLM_API_KEY}"
    model_name: "claude-opus-4-20250514"
    
  - name: "Claude Sonnet 4"
    provider: "anthropic"
    base_url: "https://api.anthropic.com/v1"
    api_key: "${LLM_API_KEY}"
    model_name: "claude-sonnet-4-20250514"
